import { normalizeCpf, validateCpf } from '../../src/utils/cpf';

describe('CPF Utils', () => {
  describe('normalizeCpf', () => {
    it('should remove dots and dashes from formatted CPF', () => {
      expect(normalizeCpf('123.456.789-00')).toBe('12345678900');
    });

    it('should remove spaces from CPF', () => {
      expect(normalizeCpf('123 456 789 00')).toBe('12345678900');
    });

    it('should handle already clean CPF', () => {
      expect(normalizeCpf('12345678900')).toBe('12345678900');
    });

    it('should handle mixed formatting', () => {
      expect(normalizeCpf('123.456.789 00')).toBe('12345678900');
    });
  });

  describe('validateCpf', () => {
    it('should validate correct CPF', () => {
      expect(validateCpf('111.444.777-35')).toBe(true);
      expect(validateCpf('11144477735')).toBe(true);
    });

    it('should reject CPF with wrong length', () => {
      expect(validateCpf('123')).toBe(false);
      expect(validateCpf('123456789012')).toBe(false);
    });

    it('should reject CPF with all same digits', () => {
      expect(validateCpf('111.111.111-11')).toBe(false);
      expect(validateCpf('000.000.000-00')).toBe(false);
      expect(validateCpf('99999999999')).toBe(false);
    });

    it('should reject CPF with invalid check digits', () => {
      expect(validateCpf('123.456.789-00')).toBe(false);
      expect(validateCpf('111.444.777-36')).toBe(false);
    });

    it('should validate formatted and unformatted CPF equally', () => {
      const formatted = '111.444.777-35';
      const unformatted = '11144477735';
      expect(validateCpf(formatted)).toBe(validateCpf(unformatted));
    });

    it('should validate known valid CPFs', () => {
      // Valid CPFs generated by algorithm
      expect(validateCpf('529.982.247-25')).toBe(true);
      expect(validateCpf('234.765.216-80')).toBe(true);
    });
  });
});
